[project]
name = "nswtransportdata"
version = "0.1.0"
description = "Stuff to do with public transport in NSW"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "blinker==1.9.0",
    "branca==0.8.2",
    "certifi==2025.10.5",
    "charset-normalizer==3.4.4",
    "click==8.3.0",
    "colorama==0.4.6",
    "flask==3.1.2",
    "folium==0.20.0",
    "gtfs-kit>=12.0.4",
    "idna==3.11",
    "isoweek==1.3.3",
    "itsdangerous==2.2.0",
    "jinja2==3.1.6",
    "markupsafe==3.0.3",
    "networkx==3.5",
    "numpy==2.3.4",
    "osmnx>=2.1.0",
    "pandas==2.3.3",
    "pandas-stubs==2.3.2.250926",
    "partridge==1.1.2",
    "pyarrow==22.0.0",
    "python-dateutil==2.9.0.post0",
    "pytz==2025.2",
    "requests==2.32.5",
    "ruff>=0.15.13",
    "scikit-learn>=1.8.0",
    "shapely>=2.1.2",
    "six==1.17.0",
    "tqdm==4.67.1",
    "tzdata==2025.2",
    "urllib3==2.5.0",
    "werkzeug==3.1.3",
    "xyzservices==2025.4.0",
]
